name: vit_ap_student_app
description: "VITAP - Student App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.2.1
  google_nav_bar: ^5.0.6
  page_transition: ^2.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  share_plus: ^9.0.0
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  lottie: ^3.1.2
  animations: ^2.0.11
  fl_chart: ^0.68.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.1+2
  font_awesome_flutter: ^10.7.0
  awesome_snackbar_content: ^0.1.3
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.1.2
  google_mobile_ads: ^5.1.0
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  wiredash: ^2.2.1
  timeago: ^3.7.0
  retry: ^3.1.2
  connectivity_plus: ^6.0.4
  wave: ^0.2.2
  permission_handler: ^11.3.1
  wifi_hunter: ^1.1.1+2
  timezone: ^0.9.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 2.4.0
  change_app_package_name: ^1.3.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/playstore.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/splash/
    - assets/images/footer/
    - assets/images/pfp/
    - assets/images/icons/
    - assets/images/lottie/
    - assets/weather_icons/
    - assets/images/login/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SourceCodePro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic

